const cats = [
  {
    name: "Sasha",
    avatar: "images/cat-sasha.jpg",
    age: 26,
    bio: "Here to make your heart skip a beat.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Ginger",
    avatar: "images/cat-ginger.jpg",
    age: 22,
    bio: "Seeking someone to share sunbeams and belly rubs with.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Oliver",
    avatar: "images/cat-oliver.jpg",
    age: 19,
    bio: "Orange tabby by day, suave detective by night.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Luna",
    avatar: "images/cat-luna.jpg",
    age: 23,
    bio: "Specializing in melting hearts and chasing sunspots..",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rusty",
    avatar: "images/cat-rusty.jpg",
    age: 18,
    bio: "Scoring treats and naps like a champ!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Tux",
    avatar: "images/cat-tux.jpg",
    age: 20,
    bio: "Here for paw-some adventures and tummy tickles.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Smokey",
    avatar: "images/cat-smokey.jpg",
    age: 21,
    bio: "Seeking deep conversations and endless chin scratches.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Cookie",
    avatar: "images/cat-cookie.jpg",
    age: 18,
    bio: "Living life one nap at a time.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Mochi",
    avatar: "images/cat-mochi.jpg",
    age: 24,
    bio: "Wise beyond my whiskers.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Sunny",
    avatar: "images/cat-sunny.jpg",
    age: 19,
    bio: "Swiping right for playdates and nap partners!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];

export default cats;
